### ISSUE TITLE
config.json doesn't exist

### ISSUE THREAD

**Issue by paul-nelson-baker** [Inumedia/SlackAPI#73]
I cannot build the project because of this error. "SlackAPI\IntegrationTest\Configuration\config.json" because it was not found.

I just did a fresh checkout to build the stock project. I assumed that the file was just accidently from git deleted, but [I couldn't restore the file](http://stackoverflow.com/a/1113140/1478636), so maybe it was just forgotten in a recent check in?

**Comment by paul-nelson-baker** [comment]
Actually, I just noticed that [you're trying to remove this file](https://github.com/Inumedia/SlackAPI/issues/70). Do we need to create this file locally? Are there instructions to do so?

**Comment by gpailler** [comment]
This file is not included in the repo because it contains sensitive informations. 
* If you only want to build SlackAPI without tests, you can exclude/unload IntegrationTest project
* If you want to add tests, compile the project and run it, you have to copy/paste config.default.json to config.json then modify values:
  * userAuthToken => Go to https://api.slack.com/docs/oauth-test-tokens to generate a token for your user
  * botAuthToken => Go to https://my.slack.com/services/new/bot to create a bot for your team and retrieve associated token
  * testChannel => Channel ID (user associated to userAuthToken must be a member of the channel)
  * directMessageUser => A slack member username
  * clientId/clientSecret/authCode are related to TestGetAccessToken test. I'm not sure about the values (specially authCode) so you can ignore this test

We will probably add some details about how to generate this file on the README later

**Comment by gpailler** [comment]
Details added in README.md
