### ISSUE TITLE
Can't connect using bot token

### ISSUE THREAD

**Issue by rhyok** [Inumedia/SlackAPI#88]
Hello!

I've been trying to utilize this library to power a bot at my company. I cannot for the life of me get it to connect using the token I got for my bot.

I built the latest master branch and dropped the DLL into my code. Here's what I'm using to connect (pulled straight from your example):
```c#
                        socketClient = new SlackSocketClient(BotToken);

			ManualResetEventSlim clientReady = new ManualResetEventSlim(false);
			socketClient.Connect((connected) => {
				// This is called once the client has emitted the RTM start command
				Console.WriteLine("rtm start");
				clientReady.Set();
			}, () => {
				// This is called once the RTM client has connected to the end point
				Console.WriteLine("endpoint connected");
			});
```

where BotToken is the string bot token I've gotten from a Bot User integration (from the field labeled "API Token"). I've also attempted to use your unit test suite and it fails when I use my token. The exact error message from your suite is "---- Took too long to do 'Connect - Connected callback'". 

I find it especially bizarre as it seems like the initial socket connection is failing silently. I'm not getting an exception or timeout or anything of the sort. I'm running on a Mac using the Mono runtime. I know for a fact that we are able to run RTM clients from within the company. Beyond us using Slack internally, I've run my bot on my local box using SlackConnector with no issue.

Any ideas why this might be failing? I generated the token about a year ago if that makes any difference.

Thanks,
Ryan

**Comment by Inumedia** [comment]
Neat. Off hand, I haven't got a clue and would need to look into it. I do
know we've had reports of RTM not working with bot auth tokens in the past,
maybe slack connector is using something other than RTM?

On Wed, Jan 11, 2017, 00:31 rhyok <notifications@github.com> wrote:

Hello!

I've been trying to utilize this library to power a bot at my company. I
cannot for the life of me get it to connect using the token I got for my
bot.

I built the latest master branch and dropped the DLL into my code. Here's
what I'm using to connect (pulled straight from your example):

                        socketClient = new SlackSocketClient(BotToken);

			ManualResetEventSlim clientReady = new ManualResetEventSlim(false);
			socketClient.Connect((connected) => {
				// This is called once the client has emitted the RTM start command
				Console.WriteLine("rtm start");
				clientReady.Set();
			}, () => {
				// This is called once the RTM client has connected to the end point
				Console.WriteLine("endpoint connected");
			});

where BotToken is the string bot token I've gotten from a Bot User
integration (from the field labeled "API Token"). I've also attempted to
use your unit test suite and it fails when I use my token. The exact error
message from your suite is "---- Took too long to do 'Connect - Connected
callback'".

I find it especially bizarre as it seems like the initial socket connection
is failing silently. I'm not getting an exception or timeout or anything of
the sort. I'm running on a Mac, and I know for a fact that we are able to
run RTM clients from within the company. Beyond us using Slack internally,
I've run my bot on my local box using SlackConnector with no issue.

Any ideas why this might be failing? I generated the token about a year ago
if that makes any difference.

Thanks,
Ryan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Inumedia/SlackAPI/issues/88>, or mute the thread

**Comment by rhyok** [comment]
Is there anything you'd try on first blush? Do you have confirmed reports of the lib working with bot tokens (assuming so, just want to make sure)? Have any knowledge of what your users have done when the token did not work?

I'll peep on SlackConnector's source if it's available.

**Comment by abergs** [comment]
Any update on this @rhyok and @Inumedia? I'm planning to build a SlackApp using .NET Core and this client

**Comment by Inumedia** [comment]
I haven't had any time to dedicate to looking into this yet, sorry ☹️

**Comment by gpailler** [comment]
Did you checked the .Net core branch and Nuget package?
I remember I faced a similar connection issue. It was related to an invalid (or mismtach) Dll in the binaries folder.
Could you check if you have any catched exception (like FileLoadException ...)

**Comment by abergs** [comment]
@gpailler I actually decided to target .net full first, just to get the basics working. I'm on a windows machine so I can still run ASP.NET CORE but on full .net.

**Comment by gpailler** [comment]
To reply on the initial issue, connection using a bot token should work. It's the purpose of the unit test `TestConnectAsBot()`. 
If it doesn't work, please ensure there is no catched exception at all in the Output Window.
